project:
  type: website
  resources:
  - scripts/site-behavior.js
  - public/**
  output-dir: docs
  render:
  - index.md
  - "content/notes/理论/**/*.md"
  - "content/notes/计算/**/*.md"
  - "content/posts/**/*.md"
  - '!**/_index.md'
  - '!**/*.ipynb'  # Exclude notebooks from rendering for speed
website:
  title: Erise Note
  navbar:
    left:
    - text: Notes
      href: content/notes/index.md
    - text: Posts
      href: content/posts/index.md
    right:
    - text: GitHub
      href: https://github.com/EriseHe/notebook
  search:
    location: navbar
    type: textbox
  sidebar:
    # Define two named sidebars as a list (correct Quarto syntax)
    - id: notes
      style: docked
      search: true
      collapse-level: 2
      contents:
      - content/notes/理论/index.md
      - auto: "content/notes/理论/**/*.md"
      - content/notes/计算/index.md
      - auto: "content/notes/计算/**/*.md"
    - id: posts
      style: docked
      search: true
      collapse-level: 2
      contents:
      - content/posts/index.md
      - auto: "content/posts/**/*.md"
format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 3
    code-link: true
    smooth-scroll: true
    mathjax: default
    lang: zh
    page-layout: full
    include-after-body:
    - scripts/site-behavior.html
execute:
  echo: false
  warning: false
  message: false
  freeze: true  # Don't re-execute code, use cached results
  daemon: false  # Disable daemon for faster rendering
  cache: true
