project:
  type: website
  resources:
  - scripts/site-behavior.js
  - public/**
  output-dir: docs
  pre-render:
  - node scripts/fix-empty-titles.js
  render:
  - index.md
  - content/notes/理论/**/*.md
  - content/notes/计算/**/*.md
  - content/posts/**/*.md
  - '!**/_index.md'
  - '!**/*.ipynb'
  - '!**/*.html'
  - '!docs/**'
website:
  title: Erise Note
  navbar:
    left:
    - text: Notes
      href: content/notes/index.md
    - text: Posts
      href: content/posts/index.md
    right:
    - text: GitHub
      href: https://github.com/EriseHe/notebook
  search:
    location: navbar
    type: textbox
  sidebar:
  - id: notes
    style: docked
    search: true
    collapse-level: 2
    contents:
    - content/notes/理论/index.md
    - auto: content/notes/理论/**/*.md
    - content/notes/计算/index.md
    - auto: content/notes/计算/**/*.md
  - id: posts
    style: docked
    search: true
    collapse-level: 2
    contents:
    - content/posts/index.md
    - auto: content/posts/**/*.md
format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 3
    code-link: true
    smooth-scroll: true
    mathjax: default
    lang: zh
    page-layout: full
    include-after-body:
    - scripts/site-behavior.html
    filters:
    - filters/auto-title.lua
    - filters/obsidian-callouts.lua
execute:
  echo: false
  warning: false
  message: false
  freeze: true
  daemon: false
  cache: true
